export const AFFIRMATIONS = [
  "I am becoming the best version of myself every single day.",
  "My confidence grows stronger with every positive choice I make.",
  "I invest in myself because I am worth it.",
  "I am disciplined, focused, and committed to my goals.",
  "My appearance reflects the care and love I give to myself.",
  "Every small habit compounds into a powerful transformation.",
  "I walk with confidence because I know my worth.",
  "I attract success by taking care of my mind, body, and spirit.",
  "I am grateful for my body and I treat it well.",
  "Growth happens when I step outside my comfort zone.",
  "I am consistent, and consistency creates results.",
  "My potential is limitless when I stay committed.",
  "I radiate health, energy, and confidence.",
  "I embrace the process of becoming a better man/woman.",
  "People notice the positive energy I bring into every room.",
  "I do the work others won't, so I can have what others don't.",
  "Every morning routine I complete is an act of self-respect.",
  "I am building habits that will serve me for a lifetime.",
  "My dedication to improvement inspires those around me.",
  "I show up for myself every single day — no exceptions.",
  "The way I present myself tells the world how I feel about myself.",
  "I am capable of incredible transformation.",
  "My glow comes from the inside and radiates outward.",
  "I choose health, confidence, and discipline every day.",
  "I am not comparing myself to others — I only compete with yesterday's me.",
  "Small improvements every day lead to massive results.",
  "I take pride in my appearance because I take pride in myself.",
  "My morning routine sets the tone for a winning day.",
  "I am patient with my progress — transformation takes time.",
  "I deserve to look and feel my absolute best.",
  "Consistency is my superpower.",
  "I am the architect of my own confidence.",
  "Every habit I build is a brick in the foundation of my best self.",
  "I face every day with energy and purpose.",
  "My self-care is a non-negotiable priority.",
  "I am proud of how far I've come and excited for where I'm going.",
  "I attract positivity by projecting positivity.",
  "I have the power to create the body and mind I desire.",
  "Discipline equals freedom — I choose discipline.",
  "I am constantly evolving, growing, and improving.",
  "My confidence is my competitive advantage.",
  "I nourish my body with food that makes me feel powerful.",
  "I sleep well because I value my recovery and growth.",
  "My presence commands respect.",
  "I am comfortable in my own skin and I love who I am becoming.",
  "Every compliment I receive reflects the effort I put in.",
  "I set goals and I follow through — that's who I am.",
  "My transformation is proof that hard work pays off.",
  "I wake up motivated because I have a vision for my life.",
  "I am exactly where I need to be on my journey.",
  "Today I will be 1% better than yesterday.",
  "My energy is contagious — I choose to make it positive.",
  "I handle challenges with grace and come out stronger.",
  "I invest my time wisely in habits that serve my highest self.",
  "I look good, feel good, and do good.",
  "My skin, my hair, my body — I take care of all of it.",
  "I am worthy of the effort it takes to become my best self.",
  "The mirror reflects someone who never stops growing.",
  "I celebrate every small win on my journey.",
  "Today is another opportunity to build the life I envision.",
  "I am unstoppable when I commit to my routines.",
];

export function getDailyAffirmation(): string {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  );
  return AFFIRMATIONS[dayOfYear % AFFIRMATIONS.length];
}
